packages:
  - apps/cli
  - apps/web
  - packages/cdk
  - packages/config
  - packages/e2e
  - packages/emails
  - packages/lint
  - packages/migration
  - packages/ui
  - packages/storybook
  - packages/test
  - packages/fixtures
