packages:
  - apps/cli
  - apps/web
  - packages/cdk
  - packages/config
  - packages/e2e
  - packages/emails
  - packages/lint
  - packages/ui
  - packages/storybook
  - packages/test
  - packages/fixtures

minimumReleaseAge: 21600
minimumReleaseAgeExclude:
  - typescript
  - react
  - react-dom
  - "@types/react"
  - "@types/react-dom"
  - next
  - "@next/env"