import type { SessionUser } from '@app/web/auth/sessionUser'
import { currentCguVersion } from '@app/web/features/cgu/currentCguVersion'

export const testSessionUser = {
  id: 'test',
  email: 'jean.biche@example.com',
  firstName: 'Jean',
  lastName: 'Biche',
  name: 'Jean Biche',
  slug: 'jean-biche',
  role: 'User',
  image: null,
  legacyId: null,
  updated: new Date('2023-05-05').toISOString(),
  created: new Date('2023-01-01').toISOString(),
  emailVerified: new Date('2023-01-01').toISOString(),
  lastCguAcceptedAt: new Date('2023-01-01').toISOString(),
  cguVersion: currentCguVersion,
  hasSeenV2Onboarding: null,
  isPublic: false,
  ownedBases: [],
  bases: [],
  createdResources: [],
  resources: [],
  collections: [],
  newsFeed: {
    themes: [],
    professionalSectors: [],
    hasCompleteOnboarding: false,
    userId: 'test',
    created: new Date('2023-01-01').toISOString(),
    updated: new Date('2023-01-01').toISOString(),
    monthlyNewsletter: false,
  },
} as const satisfies SessionUser
