name: Web application preview environment deletion on branch delete
on:
  delete
jobs:
  trigger-circleci:
    if: github.event.ref_type == 'branch'
    name: Trigger CircleCI web_app_preview_deletion workflow
    runs-on: ubuntu-latest
    steps:
      - name: Trigger CircleCI workflow
        uses: promiseofcake/circleci-trigger-action@v1
        with:
          # Branch from environment does not exists anymore, workflow will run from main branch
          branch: main
          payload: '{"trigger_workflow": "web_app_preview_deletion", "preview_deletion_branch": "${{ github.event.ref }}"}'
        env:
          CCI_TOKEN: ${{ secrets.CIRCLE_CI_TOKEN }}
